name: Cross.Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 5.0.x
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --logger trx --results-directory "TestResults" --no-restore --verbosity normal
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: TestResults
          # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
      
      # The Create Package step is unnecessary because the dotnet build step already builds it.
      - name: Add nuget source 
        run: dotnet nuget add source --username mytrout --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/mytrout/index.json"
      - name: Publish the package to GPR
        run: dotnet nuget push "./src/Cross.Core/bin/Release/*.nupkg" --source "github"